service-name: hello-world
links:
  - name: Primary Repo
    url: https://github.com/fake-org/hello-world
    type: repo
    provider: github
  - name: Outage Runbook
    url: https://fake-org.github.io/hello-world-outage-runbook
    type: runbook
    provider: confluence
  - name: API Documentation
    url: https://fake-org.github.io/hello-world-api-docs
    type: doc
    provider: github
